# Generated by Django 3.0.5 on 2020-06-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
