# Generated by Django 3.0.5 on 2020-06-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reg_no', models.CharField(max_length=16)),
                ('vehicle_color', models.CharField(max_length=100)),
                ('vehicle_brand', models.CharField(choices=[('HN', 'Honda'), ('TY', 'Toyota'), ('BMW', 'BMD'), ('MD', 'Mercedes')], max_length=32)),
                ('vehicle_image', models.ImageField(upload_to='media/')),
                ('vehicle_menufatured_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
