# Generated by Django 3.0.5 on 2020-06-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_brand',
            field=models.CharField(choices=[('BMW', 'BMD'), ('TY', 'Toyota'), ('HN', 'Honda'), ('MD', 'Mercedes')], max_length=32),
        ),
    ]
